### ISSUE TITLE
Broken output on 80 column terminal

### ISSUE THREAD

**Issue by splitbrain** [muesli/duf#10]
A default Terminal on XFCE opens with a 80 char width, which leads to a somewhat broken output:

![2020-09-21-160443_814x554_scrot](https://user-images.githubusercontent.com/86426/93776762-323b7100-fc24-11ea-9a26-d0721473ee41.png)

I guess on terminals that aren't wide enough, it would make sense to skip columns (probably the bar chart first) or shorten paths.

**Comment by edent** [comment]
This is such a beautiful tool! I came here to make the same suggestion.
Would changing `barWidth` to `10` help
https://github.com/muesli/duf/blob/master/main.go#L79

My thinking is that people can more intuitively see / count groups of 10.

![Screenshot from 2020-09-21 16-33-32](https://user-images.githubusercontent.com/837136/93787711-86e0eb00-fc28-11ea-94ac-fb89572240b0.png)

Anyway, duf is lovely. Thank you so much for it.

**Comment by muesli** [comment]
I'll try and resize / elide content to fit in the desired output terminal. PR upcoming!

**Comment by muesli** [comment]
I've just added terminal width auto-detection and word-wrapping the output to prevent this from happening. `$COLUMNS` isn't supported yet, but should be fairly trivial to add.
