### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by shirou** [muesli/duf#111]
Hi, I am an author of [gopsutil](https://github.com/shirou/gopsutil). duf is very cool tool. I love it.

However, I think this code seems very similar to gopsutil code, like

- [duf/mounts_linux.go](https://github.com/muesli/duf/blob/master/mounts_linux.go#L30)
- [gopsutil/disk/disk_linux.go](https://github.com/shirou/gopsutil/blob/master/disk/disk_linux.go#L264)

and many others.  

gopsutil is under [New BSD License](https://github.com/shirou/gopsutil/blob/master/LICENSE). It has this clause.

```
 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
```

I am not a laywer, but if you want to use gopsutil code, I think you should include this copyright notice.

**Comment by muesli** [comment]
Thanks for the heads up, added it to the `LICENSE`.
