### ISSUE TITLE
release status for the latest tag `0.6.1`

### ISSUE THREAD

**Issue by chenrui333** [muesli/duf#116]
👋 just want to quickly check on the status of the latest tag `0.6.1` (whether it is the `latest release` or `pre release`). Thanks!

---

relates to Homebrew/homebrew-core#73964 Homebrew/homebrew-core#74002

**Comment by muesli** [comment]
It will become a proper release, and the git tag already points to the right commit. The only reason it's not "properly released" just yet, is an issue on the Snap store, that prevents me from publishing all the binaries/packages. :disappointed: 

This hopefully gets resolved this weekend.
