### ISSUE TITLE
Input to next line in urxvt

### ISSUE THREAD

**Issue by obreitwi** [muesli/duf#120]
Hey, very nice tool! I just found a minor annoyance:

Similar to #84, when running `duf` in [`urxvt`](https://wiki.archlinux.org/index.php/rxvt-unicode), the next line contains undesired input:
```
$ duf --version
duf 0.6.1 (43918fe)
$ 2;1R
```

The input to the next line contains a number that is somewhat related to the number of lines printed so far (but lagging behind one command), followed by `;1R`:

```
[completely fresh terminal window]
$ duf --version
duf 0.6.1 (43918fe)
$ 2;1R<clear-line>duf --help
[...]
$ 4;1R<clear-line>duf --help
[...]
$ 36;1R<clear-line>duf --version
duf 0.6.1 (43918fe)
$ 68;1R<clear-line>duf --version
duf 0.6.1 (43918fe)
$ 70;1R
```

This does not happen in [`alacritty`](https://github.com/alacritty/alacritty) so I think it is emulator-specific and, judging from #84, might be caused by [`termenv`](https://github.com/muesli/termenv) as well.

**Comment by muesli** [comment]
Thanks, this looks similar indeed.

**Comment by muesli** [comment]
This should be fixed in v0.6.2!

**Comment by obreitwi** [comment]
Can confirm it is fixed, thank you very much!

**Comment by muesli** [comment]
Awesome, appreciate the feedback! Thank you.
