### ISSUE TITLE
Illegal Instruction on Lubuntu i386

### ISSUE THREAD

**Issue by gaurushab** [muesli/duf#121]
Lubuntu 18.04 running on Pentium III

steps:
sudo apt install golang
sudo wget https://github.com/muesli/duf/releases/download/v0.6.2/duf_0.6.2_linux_386.deb
sudo apt install ./duf_0.6.2_linux_386.deb
duf
Results in "Illegal Instruction"

also tried installing with dpkg -i and gdebi - same result
also tried 0.6.0 - same result

**Comment by IGLOU-EU** [comment]
And if you try to build from source like `go install github.com/muesli/duf@latest` ?
out put like `~/.go/bin/duf`

**Comment by gaurushab** [comment]
$ sudo go get github.com/muesli/duf
# golang.org/x/term
../../../go/src/golang.org/x/term/term_unix_linux.go:9:26: ioctlReadTermios redeclared in this block
	previous declaration at ../../../go/src/golang.org/x/term/term_unix_aix.go:9:26
../../../go/src/golang.org/x/term/term_unix_linux.go:10:27: ioctlWriteTermios redeclared in this block
	previous declaration at ../../../go/src/golang.org/x/term/term_unix_aix.go:10:27

does this mean anything to you? I suspect it may have something to do with my golang version
$ go version
go version go1.10.4 linux/386

**Comment by gaurushab** [comment]
removed golang 1.10 and installed 1.16

now "go version" returns "Illegal Instruction"

**Comment by IGLOU-EU** [comment]
You never need to use superuser (sudo), for build. Only for install on system (multi user)

Your issue can be relative to:
https://bugs.launchpad.net/ubuntu/+source/golang/+bug/1367165

?

**Comment by muesli** [comment]
This is because Go 1.16 requires SSE2, which was only introduced by the Pentium 4. If I understand it correctly, you can work around this by setting the environment variable `GO386` to `softfloat` at compile time.

**Comment by muesli** [comment]
Closing this as there's not much we can do here.
