### ISSUE TITLE
golang.org/x/crypto/ssh/terminal is deprecated

### ISSUE THREAD

**Issue by IGLOU-EU** [muesli/duf#124]
See https://dev.golang.org/release
Code : CL 170861

PR : https://go-review.googlesource.com/c/crypto/+/170861/

go-staticcheck warning :
```
package golang.org/x/crypto/ssh/terminal is deprecated: this package moved to golang.org/x/term.  (SA1019)go-staticcheck
```

Should we consider it?

**Comment by muesli** [comment]
Yeah, definitely.
