### ISSUE TITLE
leading backslash character?

### ISSUE THREAD

**Issue by OneCDOnly** [muesli/duf#125]
Hello, I've just updated to 0.6.2 from 0.6.0 (ARM64 binary running in Linux) and noticed this odd backslash appearing before the regular text:

![image](https://i.imgur.com/H7Fd0n6.png)

![image](https://i.imgur.com/cMwdVMs.png)

Might be a typo?

**Comment by muesli** [comment]
Which terminal are you using?

**Comment by OneCDOnly** [comment]
Ah, good point. I'm using Konsole 18.04.0 on Debian 10.9.

So, I've now tested with a bunch of other terminals and they all work fine. This problem appears limited to Konsole. I guess there something in my current config affecting this. 😞 

Any pointers as to what I should be looking for? Thank you.

**Comment by OneCDOnly** [comment]
A bit more testing: I've reset Konsole to using a default profile - same issue. 

I've downloaded the previous `duf` versions to see when this started. There's no-problem with 0.5.0 and 0.6.0. It begins with 0.6.1.

**Comment by OneCDOnly** [comment]
I'm just now downloading and installing Debian testing to try a later Konsole version. I'll post back when it's done. 👍🏽

**Comment by OneCDOnly** [comment]
Yup, it was my old version of Konsole that was the issue here. Using Konsole 20.12.3 works fine. 

Apologies for the trouble @muesli and thank you for your patience.
