### ISSUE TITLE
Not expected results for specific path

### ISSUE THREAD

**Issue by manueljordan** [muesli/duf#127]
Hello

I just installed this nice software in Ubuntu Desktop (VirtualBox) 18.04

```
duf --version
duf 0.6.2 (d1d2865)
```

The reason of this post is: 

For both `duf` and `duf /home` - they always show the same following result, therefore the latter works showing the same output than the former

```
╭────────────────────────────────────────────────────────────────────────────────────────╮
│ 1 local device                                                                         │
├────────────┬───────┬───────┬───────┬───────────────────────────────┬──────┬────────────┤
│ MOUNTED ON │  SIZE │  USED │ AVAIL │              USE%             │ TYPE │ FILESYSTEM │
├────────────┼───────┼───────┼───────┼───────────────────────────────┼──────┼────────────┤
│ /          │ 14.7G │ 10.4G │  3.6G │ [##############......]  70.7% │ ext4 │ /dev/sda1  │
╰────────────┴───────┴───────┴───────┴───────────────────────────────┴──────┴────────────╯
```

Other case: for example for `duf /home ~/Downloads/ /etc/` it shows:

```
╭────────────────────────────────────────────────────────────────────────────────────────╮
│ 3 local devices                                                                        │
├────────────┬───────┬───────┬───────┬───────────────────────────────┬──────┬────────────┤
│ MOUNTED ON │  SIZE │  USED │ AVAIL │              USE%             │ TYPE │ FILESYSTEM │
├────────────┼───────┼───────┼───────┼───────────────────────────────┼──────┼────────────┤
│ /          │ 14.7G │ 10.4G │  3.6G │ [##############......]  70.7% │ ext4 │ /dev/sda1  │
│ /          │ 14.7G │ 10.4G │  3.6G │ [##############......]  70.7% │ ext4 │ /dev/sda1  │
│ /          │ 14.7G │ 10.4G │  3.6G │ [##############......]  70.7% │ ext4 │ /dev/sda1  │
╰────────────┴───────┴───────┴───────┴───────────────────────────────┴──────┴────────────╯
```

I would assume see in `MOUNTED ON` each path (`/home - ~/Downloads/ - /etc/`) instead of `/` and of course different `use%` values (same for other columns)

What is wrong?

**Comment by IGLOU-EU** [comment]
Can you send the result of `df` ?
I think you don't have other partition.

**Comment by manueljordan** [comment]
Yes, there is only one, just `/`, I am working with VirtualBox. 

The point was that for `duf /home ~/Downloads/ /etc/` I expected to see in the output each path (`/home ~/Downloads/ /etc/`) by line and showing the amount used for each one - and of course `MOUNTED ON` yet - So I think is missing include a header such as `path` - So, the order expected about headers would be: `MOUNTED ON`, `PATH`, etc ...

**Comment by IGLOU-EU** [comment]
`duf` (Disk Usage/Free Utility) is like `df` (Report file system disk space usage), and you will get relatively the same result.
`du` "for estimate file space usage", is not like disk usage utility.

So the behavior of `duf` seems correct to me 🤔

**Comment by manueljordan** [comment]
Yes, I read incorrectly about in the _Usage_ section

```
If you supply arguments, duf will only list specific devices & mount points:

duf /home /some/file
```
