### ISSUE TITLE
Only runs as root in Pop! OS (Ubuntu) 20.10

### ISSUE THREAD

**Issue by jrusnacko** [muesli/duf#128]
Installed the latest release through apt

`sudo apt install ./duf_0.6.2_linux_amd64.deb`

duf outputs a gibberish string when run as a user, yet runs fine as root. Is this the intended behavior? (see screenshot)
![Screenshot from 2021-05-10 10-41-40](https://user-images.githubusercontent.com/52792350/117631617-b5daab80-b17c-11eb-8406-6e11cb5e8815.png)

**Comment by muesli** [comment]
No, certainly not the intended behavior. The string you're seeing here is duf querying your terminal emulator for its current output setting (default background color to be specific). There's absolutely no reason this shouldn't work as a regular user. Which terminal is this running in?

**Comment by jrusnacko** [comment]
I use Terminator, but was able to reproduce this behavior with gnome-terminal as well. However, I found that the reason this is happening is probably the [xonsh](https://xon.sh/) shell I am running - with bash, duf works fine as a regular user (both with gnome-terminal and Terminator).

**Comment by muesli** [comment]
This has been reported to xonsh and was apparently fixed recently.
