### ISSUE TITLE
Save Unicode output as png

### ISSUE THREAD

**Issue by gk7279** [muesli/duf#132]
Hi-

Is there a way to redirect the colorful Unicode output into a PNG or text file by preserving the colors?

Thanks

**Comment by muesli** [comment]
You can redirect the output to a textfile just like you would do with any other tool. There's one issue tho: duf detects that it's not writing to a terminal and disables the colored output. I think you should still be able to enforce it by setting the environment variable `CLICOLOR_FORCE=true`.

Alternatively you could look into using a tool like termshot.
