### ISSUE TITLE
go build don't install duf

### ISSUE THREAD

**Issue by mjobuda** [muesli/duf#134]
according to the readme.md a `go build` should put duf into the path.
This did not happen on my system.
after a succesful build I can do a
`./duf`
That works fine,
but `duf` does not work.
Side note: there is also no `duf` alias in my zsh(in contrary what is in the readme here)
```
ttt:~:% duf
zsh: command not found: duf
ttt:~:% unalias duf

unalias: no such hash table element: duf
```

**Comment by muesli** [comment]
> according to the readme.md a `go build` should put duf into the path.

That's from the "build from source" instructions, but I don't see where it says it would put `duf` in your `PATH`?
You can simply copy the binary anywhere you like however.

> Side note: there is also no `duf` alias in my zsh(in contrary what is in the readme here)

Are you also using `oh-my-zsh`?
