### ISSUE TITLE
Help page shows flags that don't work

### ISSUE THREAD

**Issue by 19wolf** [muesli/duf#137]
I'm very confused right now. 

- When I do `duf -help` I get output like this https://pastebin.com/mLx4QDH6
- When I do `duf -only-mp` I get `flag provided but not defined` even though it's in the documentation on the Readme.md
- If I follow the help page and do `duf -only-fs /,/data` or `duf -only-fs /dev/sda` it just returns without printing anything
- `duf -hide-fs /var/lib/docker/btrfs` it prints anyway. Same with `duf -hide-fs /dev/sda`

`duf -version` = `uf 0.6.2 (d1d2865)`

Also is it `duf -flag` or `duf --flag`, both seem to work and the documentation is very inconsistent.

I just want to display only my `/` and `/data` mount points (for my motd script).

**Comment by muesli** [comment]
>     * When I do `duf -only-mp` I get `flag provided but not defined` even though it's in the documentation on the Readme.md

`--only-mp` and `--hide-mp` haven't been part of a stable release yet, but looking at the documentation on GitHub you're obviously looking at the latest development state of the documentation.

> Also is it `duf -flag` or `duf --flag`, both seem to work and the documentation is very inconsistent.

Both work.

> I just want to display only my `/` and `/data` mount points (for my motd script).

You can still call `duf` like this: 

```bash
duf / /data
```
