### ISSUE TITLE
duf in snap can't start, error: "-bash: duf: command not found"

### ISSUE THREAD

**Issue by R8s6** [muesli/duf#148]
Hi,

I'm on proxmox (based on debian, think of it as debian 11 with a custom repo).

I installed snapd then did: `sudo snap install duf-utility`. I verified that `duf-utility` had been installed:

```
$ sudo snap list
Name         Version   Rev    Tracking       Publisher   Notes
core20       20210928  1169   latest/stable  canonical✓  base
duf-utility  v0.6.0    1      latest/stable  muesli      -
snapd        2.52.1    13640  latest/stable  canonical✓  snapd
```

But when I ran `duf` I got this error:
```
$ duf
-bash: duf: command not found
```

Running as root gave the same error.

Is this a packaging issue or perhaps something else?

Thanks!

**Comment by muesli** [comment]
This looks like a packaging issue indeed. Sadly the `snap` package isn't properly maintained at this point, as snap's sandbox doesn't allow for the required permissions currently. I should probably remove the snap package from the README.

**Comment by R8s6** [comment]
Thanks for the update.

Any possibilities of packaging for flatpak or perhaps docker? These two can be installed on any distro.

If that's too much work, no worries, thanks for the hard work, I enjoy this software very much (on Arch btw ;-) )!

**Comment by muesli** [comment]
> Any possibilities of packaging for flatpak or perhaps docker? These two can be installed on any distro.

Similar issues potentially, as duf needs to be able to identify actual block devices and retrieve info about physical disks from `/proc`. As you can imagine sandboxing / virtualization is an issue in that regard. We can look into this however.

> If that's too much work, no worries, thanks for the hard work, I enjoy this software very much (on Arch btw ;-) )!

pacman -S duf

:smiley:

**Comment by muesli** [comment]
Here's the good news: on recent Debian & Ubuntu installs you can now simply run `apt install duf`.

**Comment by muesli** [comment]
Closing this one, as we'll have to wait for upstream to fix the situation.

**Comment by R8s6** [comment]
Thank you very much!
