### ISSUE TITLE
Thanks for the man page, but it is obsolete before first use!

### ISSUE THREAD

**Issue by alerque** [muesli/duf#152]
https://github.com/muesli/duf/blob/af580c4fff25d0337cc1ca2c2da348c57398d9b2/duf.1#L1

This needs to go on a pre-release checklist to be bumped before a release is tagged...

OR a build rule of some kind should be made that can properly set it at build time (including respecting [`$SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/)) in a consistent way across distros.

**Comment by muesli** [comment]
Apologies, that's indeed something I overlooked. Will try to fix this in a v0.7.1 asap.
