### ISSUE TITLE
Cannot build duf

### ISSUE THREAD

**Issue by mikemadden42** [muesli/duf#156]
I get this error when I try to build/install the latest version of `duf`.

```bash
$ go install github.com/muesli/duf@latest
go install: github.com/muesli/duf@latest (in github.com/muesli/duf@v0.7.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

```
$ go version
go version go1.17.6 darwin/amd64

$ sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
```

**Comment by mikemadden42** [comment]
This could be related to this issue:
https://github.com/golang/go/issues/44840

**Comment by mikemadden42** [comment]
Using `go get` is a workaround.  However this is deprecated and likely will not work long term.

```
$ go get github.com/muesli/duf@latest
go: downloading github.com/muesli/duf v0.7.0
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading git.iglou.eu/Imported/go-wildcard v1.0.1
go: downloading github.com/jedib0t/go-pretty/v6 v6.2.4
go: downloading github.com/muesli/termenv v0.9.0
go: downloading golang.org/x/sys v0.0.0-20210414055047-fe65e336abe0
go: downloading golang.org/x/term v0.0.0-20210406210042-72f3dc4e9b72
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/mattn/go-isatty v0.0.13
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Comment by muesli** [comment]
@IGLOU-EU Sounds like we need to get rid of the replace directive in go.mod after all. Would it be unreasonable to ask you to make github.com the canonical source of the go-wildcard package? Alternatively we can switch to using your self-hosted git server directly. But, even tho I'm a fan of self-hosting, I'm worried this might have a bigger impact than anticipated, especially during release time. What do you think?

**Comment by IGLOU-EU** [comment]
What would you think about including "go-wildcard" like a sub package of duf ?
But I can migrate it to github, I was wondering about this recently.

**Comment by muesli** [comment]
> What would you think about including "go-wildcard" like a sub package of duf ?

I wouldn't mind that, but...

> But I can migrate it to github, I was wondering about this recently.

... this probably gives the package more exposure and users in the long run.

It's totally up to you tho!

**Comment by muesli** [comment]
Should be fixed in `master` and work with `latest` as soon as I release `v0.7.1`.
