### ISSUE TITLE
Installation error on Ubuntu - Unable to locate package duf

### ISSUE THREAD

**Issue by raisedadead** [muesli/duf#181]
I am getting the below error on Ubuntu:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1884376/174139246-17f36870-d079-48de-a453-b7114aa26888.png">

I followed the install command here: https://github.com/muesli/duf#linux

Do I need to add a repository for the PPA?

**Comment by raisedadead** [comment]
homebrew (via linuxbrew) works fine BTW.

**Comment by d3lac** [comment]
I get the same error with Debian 11.

```
sudo apt install duf -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package duf
```

**Comment by muesli** [comment]
It should be available for Ubuntu 22.04 and Debian unstable.

**Comment by raisedadead** [comment]
Mind if I create a quick PR making a note of it in the instructions?

**Comment by muesli** [comment]
> Mind if I create a quick PR making a note of it in the instructions?

Please do!

**Comment by wolf99** [comment]
I am seeing this for Ubuntu 22.04

```console
~❯ sudo apt update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 336 kB in 1s (556 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.

~❯ sudo apt install duf
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package duf

~❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

**Comment by wolf99** [comment]
Ah! Oops, my bad, I misread the requirement! 🤦

**Comment by muesli** [comment]
> Ah! Oops, my bad, I misread the requirement! facepalm

Don't worry, been there and done that myself :laughing:

**Comment by huanfachen** [comment]
The `apt install duf` does not work for Ubuntu 20.04. Here is the solution for installing this duf package (on Ubuntu 20.04 WSL):

1. Download the binary file of [duf_0.8.1_linux_arm64.tar.gz](https://github.com/muesli/duf/releases/download/v0.8.1/duf_0.8.1_linux_arm64.tar.gz) from [here](https://github.com/muesli/duf/releases).
2. Use `tar -xzvf duf_0.8.1_linux_arm64.tar.gz` to extract the binary duf file.
3. Copy the duf file to the folders of **/usr/bin** and **/bin**.
4. Then the duf command works on the terminal.

**Comment by l-33ter** [comment]
> The `apt install duf` does not work for Ubuntu 20.04. Here is the solution for installing this duf package (on Ubuntu 20.04 WSL):
> 
> 1. Download the binary file of [duf_0.8.1_linux_arm64.tar.gz](https://github.com/muesli/duf/releases/download/v0.8.1/duf_0.8.1_linux_arm64.tar.gz) from [here](https://github.com/muesli/duf/releases).
> 2. Use `tar -xzvf duf_0.8.1_linux_arm64.tar.gz` to extract the binary duf file.
> 3. Copy the duf file to the folders of **/usr/bin** and **/bin**.
> 4. Then the duf command works on the terminal.

sadly not on an WSL-Debian12

```
panic: runtime error: index out of range [11] with length 11

goroutine 1 [running]:
main.parseMountInfoLine({0x4000172000, 0xb8})
        github.com/muesli/duf/mounts_linux.go:165 +0x2f4
main.mounts()
        github.com/muesli/duf/mounts_linux.go:61 +0x18c
main.main()
        github.com/muesli/duf/main.go:166 +0x274
```
