### ISSUE TITLE
panic running `duf` in WSL2 in windows11

### ISSUE THREAD

**Issue by Equationzhao** [muesli/duf#241]
```bash
~ > duf                                                                 
panic: runtime error: index out of range [11] with length 11

goroutine 1 [running]:
main.parseMountInfoLine({0xc0000d6180?, 0x0?})
        github.com/muesli/duf/mounts_linux.go:165 +0x299
main.mounts()
        github.com/muesli/duf/mounts_linux.go:61 +0x17e
main.main()
        github.com/muesli/duf/main.go:166 +0x1d3
```

system info
```
OS: Arch Linux on Windows 10 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2
Uptime: 17 hours, 24 mins
Shell: zsh 5.9
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: Windows Terminal
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: b9e7:00:00.0 Microsoft Corporation Basic Render          
Memory: 2850MiB / 32049MiB
```

**Comment by Equationzhao** [comment]
![image](https://user-images.githubusercontent.com/75521101/232380789-fd206dcf-76b2-4c9a-9832-426a47a2899e.png)
perhaps it's caused by docker

**Comment by muesli** [comment]
Wild!

**Comment by IGLOU-EU** [comment]
hi @Equationzhao 

https://linux.die.net/man/5/fstab
'If the name of the mount point contains spaces these can be escaped as '\040'. '

Like you can see, into fstab space are escaped like this '\040'. But I have missed that you can have escaped space into options, and we actually don't support quoted string.

You probably need to report it to docker.

**Comment by huyz** [comment]
Anyone know of a workaround?
