### ISSUE TITLE
Small gotcha: `duf` alias already exists in default .oh-my-zsh

### ISSUE THREAD

**Issue by chaimpeck** [muesli/duf#28]
```
❯ grep duf ~/.oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh
alias duf='du -sh *'
```

**Comment by SuperSandro2000** [comment]
I think the right move would be that you just remove that alias.

``unalias duf``

**Comment by muesli** [comment]
Yeah, that's really unfortunate. But frankly, the way oh-my-zsh goes about their aliases I'd be surprised if there's any 3 or 4 letter combination they haven't occupied yet :disappointed: Just look at all the git aliases they litter your shell with.

I even tried to do something about it (see https://github.com/ohmyzsh/ohmyzsh/issues/5721#issuecomment-271020018), but eventually got to fed up with oh-my-zsh's approach. I better stop rumbling now :laughing:

**Comment by chaimpeck** [comment]
Cool, mostly wanted to note as a "gotcha" for other .oh-my-zsh users who might:
```
brew install muesli/homebrew-tap/duf
duf
...
# this doesn't look right....
```
as I did.

It might be good to add a "note to oh-my-zsh users" in the readme

**Comment by muesli** [comment]
Added a note to the README. Thanks for bringing this to my attention, @chaimpeck!
