### ISSUE TITLE
Color doesn't work in kitty.

### ISSUE THREAD

**Issue by fennecdjay** [muesli/duf#34]
Unless `TERM` is set to set `xterm-256color`, duf outputs black and white information.

`/usr/lib/terminfo/k/kitty` is present (the whole directory is symlinked from `/usr/share/terminfo` in archlinux).

It works fine in st.

Seems related to #5.

**Comment by muesli** [comment]
I'm afraid I can't actually reproduce that here.

Hence, a bunch of annoying questions :laughing:

1. Which version of kitty are you running on which platform?
2. What is your $TERM set to?
3. What is your $COLORTERM set to?
4. What is your $COLORFGBG set to?

**Comment by fennecdjay** [comment]
No problem :smile:

```sh
❯ echo -e "$(kitty -v)\n$TERM\n$COLORTERM"
kitty 0.19.1 created by Kovid Goyal
xterm-kitty
yes
```
Yet, besides `COLORTERM` I have no environment variable starting with `COLOR`, and nothing colo related in my `.zshrc`.

I'm running archlinux.

Hope this helps.

**Comment by muesli** [comment]
$COLORTERM is set to `yes`? Try and set it to `truecolor`.

**Comment by fennecdjay** [comment]
setting `$COLORTERM` to `truecolor` does work :tada:
I have no idea though how it gets set to `yes` or wether I should set it to `truecolor` in my rc files.

**Comment by muesli** [comment]
I would recommend setting it to `truecolor`. I'm going to assume 8-bit color support if it's set to any other value, but `no` or `false` (fixing that just now).
