### ISSUE TITLE
Add ? as sinonim for --help, and these two on Help message

### ISSUE THREAD

**Issue by Porrumentzio** [muesli/duf#36]
`duf --help` and `duf ?` should make the same.

Also it would be good to add `--help` and `?` on Help message (main.go)

**Comment by raygervais** [comment]
If this is wanted, I'd like to add this feature in.

**Comment by muesli** [comment]
I'm not necessarily opposed, but typically `?` is a wildcard on the shell, so this could be problematic. I also can't think of any other cli-tool that behaves like that. Any examples?

**Comment by Porrumentzio** [comment]
1) `$ alsamixer`
2) `?`
![irudia](https://user-images.githubusercontent.com/61913683/94949000-8544dc00-04e0-11eb-8134-15f552e9932a.png)

1) `$ htop`
2) `?`
![irudia](https://user-images.githubusercontent.com/61913683/94949405-2895f100-04e1-11eb-85f0-9ba968f46556.png)


I think there will be more, but I don't use many CLI apps. Anyway, most of them does not work as arguments when running, but as in-run arguments.

**Comment by muesli** [comment]
Agreed, inside a TUI it's pretty common, but I don't think I've ever seen it as a command-line argument (except on Windows maybe).

**Comment by raygervais** [comment]
Agreed, in a TUI it makes complete sense (see NNN for another example), but not in a CLI-based app.

**Comment by muesli** [comment]
Alright, I think we can close this after this discussion / conclusion. Thanks for the feedback, everyone.
