### ISSUE TITLE
Feature request: "-hide-overlay" option

### ISSUE THREAD

**Issue by achimnol** [muesli/duf#39]
First, thanks for this greate enhancements to `df`!

On hosts with many docker containers, overlay filesystems are listed under the "local" section and shows *duplicate* space information of their mother filesystem.
How about adding `-hide-overlay` option and set it true by default?
Or maybe we could split overlay filesystems under a separate section.

**Comment by achimnol** [comment]
#38 could be an alternative solution to my feature request.

**Comment by muesli** [comment]
Yeah, I think we should probably group them into a separate section. My main motivation to write this was `df`'s output being too messy after all :smiley:

**Comment by muesli** [comment]
I've changed duf's behavior to hide overlays per default, as I hardly ever consider them relevant in the context of a disk-free utility. You can still show them with `--all`, of course.
