### ISSUE TITLE
Question: Why is AVAIL of small partitions always shown in red

### ISSUE THREAD

**Issue by ashwinvis** [muesli/duf#4]
![](https://user-images.githubusercontent.com/9155111/93737826-6bec8780-fbe4-11ea-97c6-5e2051f95304.png)

See the `/boot` partition above, where the available space is shown in red colour, eventhough the usage is only 18.5%. Is this intentional?

**Comment by muesli** [comment]
You'll be able to freely configure the thresholds in a future release, but for now:

>50% usage => yellow
>90% usage => red

As well as:

<1GB => red
<10GB => yellow

**Comment by splitbrain** [comment]
I'm not sure the second list rules make sense. A partition that's smaller than 1GB will always be red.

**Comment by Dean-Coakley** [comment]
@muesli I took a look at making these thresholds configurable, but couldn't see how. Can you give some advice on how I could do that?

What would you think about removing the latter rules? 
Red implies critical warning, right? - Seems strange to warn about a partition that is 0.9GB large and 0.89GB free.

**Comment by muesli** [comment]
@Dean-Coakley You can find the two switch cases which define the output color here:

https://github.com/muesli/duf/blob/ef3c542a44005cce3bcc62fefd644d826fd2cda2/table.go#L150

and

https://github.com/muesli/duf/blob/ef3c542a44005cce3bcc62fefd644d826fd2cda2/table.go#L180

I appreciate any experiments to make this a bit cleverer!
