### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by nu8** [muesli/duf#42]
It seems it is not currently possible to build from Windows. 

~~~
.\filesystems.go:4:5: undefined: isNetworkFs
.\filesystems.go:7:5: undefined: isSpecialFs
.\filesystems.go:10:5: undefined: isFuseFs
.\main.go:60:6: undefined: isNetworkFs
.\main.go:64:6: undefined: isFuseFs
.\main.go:68:6: undefined: isSpecialFs
.\main.go:162:22: undefined: mounts
.\mounts.go:27:13: undefined: unix.Statfs_t
~~~

**Comment by muesli** [comment]
That's correct. As mentioned in the README there's support for Linux, FreeBSD, OpenBSD, and macOS. If someone wants to work on Windows support I'm not opposed to it, but I don't plan to do so personally.

**Comment by RangerCD** [comment]
Working on Windows implementation, and most of the functionalities could be supported. 
I'm currently stuck at a table display issue on Windows terminal, probably related to `go-pretty`.

**Comment by muesli** [comment]
@RangerCD Awesome! We may have to enable ANSI output for Windows consoles first, otherwise the output would be garbled. Luckily that's pretty easy, here's how I do that in another project: https://github.com/charmbracelet/glow/blob/master/console_windows.go

**Comment by nu8** [comment]
Windows Terminal has had both Unicode and ANSI escape code support since at least July 2019:

https://github.com/microsoft/terminal/releases/tag/v0.2.1715.0

**Comment by muesli** [comment]
@nu8 At least for the regular `Command Prompt` you'll still have to enable it manually. Not sure about PowerShell or their new Terminal app.

**Comment by RangerCD** [comment]
It turns out to be a code page issue. Everything works fine after I changed code page to 437(United States) or 65001(UTF-8).
![image](https://user-images.githubusercontent.com/6872198/94995707-b1d92080-05d2-11eb-8b84-f573c3e114e2.png)
Basic functionalities for local drives are adapted, maybe I should start another issue as a Windows support roadmap.

**Comment by RangerCD** [comment]
#58 adds Windows support. Feel free to test and report 😄
