### ISSUE TITLE
ascii graphics for non-UTF terminals

### ISSUE THREAD

**Issue by yermulnik** [muesli/duf#49]
I do understand this is not something common nowadays but I still have a few servers I maintain that have no UTF support in console. Hence with a little hope I'd like to ask for support for non-UTF terminals by using ascii graphics instead of UTF symbols. Thanks in advance.
![image](https://user-images.githubusercontent.com/1274789/94792322-7b887f00-03e1-11eb-83bf-b1496b673862.png)

**Comment by muesli** [comment]
That doesn't seem to be a problem with (just) the unicode output, but it also seems to misinterpret some ANSI escape sequences. Which terminal is this? I'll add a style flag which lets you fall back to common ASCII characters for the table markup.

**Comment by yermulnik** [comment]
I'm using iTerm2 on Macos and have two profiles: one is the Default with `Character encoding` set to Unicode and the other profile set to KOI8 so that koi8 chars appear as normal for those non-UTF-aware servers I mentioned. This is not terminal specific trouble as when I ssh from UTF-aware Linux server to those KOI8-only servers I hit the same issue: non-UTF symbols are not printed properly because of missing locale.

> I'll add a style flag which lets you fall back to common ASCII characters for the table markup.


Awesome! Thank you!

**Comment by muesli** [comment]
@yermulnik There's now a `--style` flag, which lets you disable these characters.

Example: `duf --style ascii`

**Comment by yermulnik** [comment]
@muesli Thanks a lot! 🎉  Anytime soon the new release is coming out?

**Comment by muesli** [comment]
@yermulnik This weekend!

**Comment by yermulnik** [comment]
Here's something new appeared with the `0.4.0` release:
```
> duf >/dev/null
/sys/kernel/debug/tracing: permission denied
```
Is this known issue or should I go with new issue creation?

```
> ls -la /sys/kernel/debug/tracing
ls: cannot access '/sys/kernel/debug/tracing': Permission denied

> ls -ld /sys/kernel/debug
drwx------ 36 root root 0 Sep  2 12:34 /sys/kernel/debug
```
```
OS: Linux Mint 18.3 Sylvia x86_64
Kernel: 4.4.0-189-generic
```

ps: `duf` itself works as expected along with new `--style ascii` flang functionality! :tada:

**Comment by yermulnik** [comment]
@muesli Should I create issue for `/sys/kernel/debug/tracing` permissions issue or this is a known issue?
