### ISSUE TITLE
Colour is turned off on screen-256color

### ISSUE THREAD

**Issue by melissaboiko** [muesli/duf#5]
Colour output works automatically on `xterm-256color`, but not `screen-256color` .

![Bildschirmfoto vom 2020-09-21 08-46-15](https://user-images.githubusercontent.com/74593/93738822-06e66100-fbe7-11ea-90b7-dcf28091dc53.png)
![Bildschirmfoto vom 2020-09-21 08-46-34](https://user-images.githubusercontent.com/74593/93738823-0948bb00-fbe7-11ea-8218-0061d567f456.png)

`/lib/terminfo/s/screen-256color` is present as normal, `infocmp` works for it.

thanks for the software 🙏

**Comment by muesli** [comment]
Can you try and unset your env var `COLORTERM` before running `duf` in `screen`?

For example: `COLORTERM="" duf`
