### ISSUE TITLE
OpenBSD Partitions (probably the same with other *BSD)

### ISSUE THREAD

**Issue by gonzalo-** [muesli/duf#69]
Hello,

I just made a port of duf for OpenBSD (pretty nice!), I realised that with only one disk (or drive) with for example 4 partitions (sd0a, sd0b, sd0d, sd0e) duf detects this as 4 drives, but actually is only one with 4 partitions.

**Comment by muesli** [comment]
This sounds like desired behavior. Wouldn't you want to see the available space for each of these devices? If I'm misunderstanding this, maybe you could post a screenshot or elaborate a bit more how you would like it to behave? Thank you!

**Comment by gonzalo-** [comment]
Hey, my example is a machine or vm with only 1 disk (drive or hdd) and for example 4 partitions /, /home/, /tmp and /var, on duf you can see that as 4 drives and not as I understand as one drive and 4 partitions or slices.

**Comment by muesli** [comment]
duf has no notion of a "drive", it shows you all mounted devices. If you have a drive with four partitions, then that accounts for four mounted devices, each with its individual filesystem that's filled independently of the other filesystems on the same drive. This is expected & desired behavior. What output are you expecting instead?

**Comment by gonzalo-** [comment]
>If you have a drive with four partitions, then that accounts for four mounted devices, each with its individual filesystem 

No, this makes sense, thanks!
