### ISSUE TITLE
Is there (or will be) a way to check size of specific dir (du functionality)?

### ISSUE THREAD

**Issue by horseinthesky** [muesli/duf#71]
Doesn't seem to work right now.
![image](https://user-images.githubusercontent.com/19948672/95740212-c8e3d680-0c94-11eb-8b62-5dfdeb0769ce.png)

**Comment by muesli** [comment]
Yeah, that's the plan!

**Comment by muesli** [comment]
Just to clarify: duf will not become an alternative for `du`. It will however support filtering devices by a path argument, like `df` does. I'll track this feature in #78.
