### ISSUE TITLE
Can't tap repository on MacOs with Homebrew

### ISSUE THREAD

**Issue by boajer** [muesli/duf#90]
Hi guys, 

While acting according to https://github.com/muesli/duf/blame/master/README.md#L34 and trying to install tool with Homebrew on MacOs, can't do that as 
```
brew tap muesli/tap                    
Updating Homebrew...
==> Tapping muesli/tap
Cloning into '/usr/local/Homebrew/Library/Taps/muesli/homebrew-tap'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 45 (delta 20), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (45/45), 7.21 KiB | 2.40 MiB/s, done.
Resolving deltas: 100% (20/20), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/muesli/homebrew-tap/deckmaster.rb
formulae require at least a URL
Error: Cannot tap muesli/tap: invalid syntax in tap!
```

at MacOs 10.15.7 && Homebrew 2.5.9

**Comment by muesli** [comment]
Hm, this should have been fixed tonight: https://github.com/muesli/homebrew-tap/pull/3

Can you confirm this is still happening right now?

**Comment by boajer** [comment]
@muesli  I can confirm, that happens at the moment I wrote this comment

``` oat date
Thu Nov 12 13:47:14 +03 2020
➜  oat brew tap muesli/tap && brew install duf
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Tapping muesli/tap
Cloning into '/usr/local/Homebrew/Library/Taps/muesli/homebrew-tap'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 45 (delta 20), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (45/45), 7.21 KiB | 3.60 MiB/s, done.
Resolving deltas: 100% (20/20), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/muesli/homebrew-tap/deckmaster.rb
formulae require at least a URL
Error: Cannot tap muesli/tap: invalid syntax in tap!```

**Comment by muesli** [comment]
Thank you, I've removed the broken formula until we've figured out a solution!

**Comment by nikolay** [comment]
@muesli I think the best and easiest for you is to have 3 taps - one for projects supported on all platform, and two others - Linux-only and macOS-only (if you have any). I don't think Homebrew and GoReleaser support mixing Linux-only formulae in a tap. The `depends_on :linux` is more of a filter for Linuxbrew (now called "Hombrew on Linux") only. Maybe I should open an issue with Homebrew similarly to the issue I opened with GoReleaser.
